#include "token_type.h"

static const char* const _TokenTypeTranslation[] =
{
  [UNINITIALIZED] = "UNINITIALIZED",

  [I8]  = "I8", [I16] = "I16", [I32] = "I32", [I64] = "I64",
  [U8]  = "U8", [U16] = "U16", [U32] = "U32", [U64] = "U64",
  [F32] = "F32", [F64] = "F64",
  [CHAR] = "CHAR", [STRING] = "STRING",
  [BOOL] = "BOOL",
  [VOID] = "VOID",
  [ENUM] = "ENUM",
  [STRUCT] = "STRUCT",
  [IF] = "IF", [ELSE] = "ELSE", [WHILE] = "WHILE", [FOR] = "FOR",
  [BREAK] = "BREAK", [CONTINUE] = "CONTINUE", [RETURN] = "RETURN",

  [IDENTIFIER] = "IDENTIFIER",

  [HEX_CONSTANT] = "HEX",
  [BINARY_CONSTANT] = "BINARY",
  [INT_CONSTANT] = "INT",
  [FLOAT_CONSTANT] = "FLOAT",
  [ENUM_CONSTANT] = "ENUM",
  [CHAR_CONSTANT] = "CHAR",

  [STRING_LITERAL] = "STRING_LITERAL",

  [LCURLY] = "LCURLY", [RCURLY] = "RCURLY",
  [LPAREN] = "LPAREN", [RPAREN] = "RPAREN",
  [LBRACKET] = "LBRACKET", [RBRACKET] = "RBRACKET",
  [PERIOD] = "PERIOD", [COMMA] = "COMMA", [SEMICOLON] = "SEMICOLON",
  [PLUS] = "PLUS", [MINUS] = "MINUS", [ASTERISK] = "ASTERISK", [DIVIDE] = "DIVIDE", [MODULO] = "MODULO",
  [TILDE] = "TILDE", [CIRCUMFLEX] = "CIRCUMFLEX", [AMPERSAND] = "AMPERSAND", [PIPE] = "PIPE",
  [EXCLAM] = "EXCLAM", [QUESTIONMARK] = "QUESTIONMARK",
  [LESS_THAN] = "LESS_THAN", [GREATER_THAN] = "GREATER_THAN",
  [EQUALS] = "EQUALS",
  [PLUS_EQUALS] = "PLUS_EQUALS", [MINUS_EQUALS] = "MINUS_EQUALS", [TIMES_EQUALS] = "TIMES_EQUALS", [DIVIDE_EQUALS] = "DIVIDE_EQUALS", [MODULO_EQUALS] = "MODULO_EQUALS",
  [XOR_EQUALS] = "XOR_EQUALS", [AND_EQUALS] = "AND_EQUALS", [OR_EQUALS] = "OR_EQUALS",
  [PLUS_PLUS] = "PLUS_PLUS", [MINUS_MINUS] = "MINUS_MINUS",
  [LEFT_SHIFT] = "LEFT_SHIFT", [RIGHT_SHIFT] = "RIGHT_SHIFT",
  [LEFT_SHIFT_EQUALS] = "LEFT_SHIFT_EQUALS", [RIGHT_SHIFT_EQUALS] = "RIGHT_SHIFT_EQUALS",

  [ERROR] = "ERROR",
  [TOKEN_EOF] = "EOF"
};

const char *TokenTypeTranslation(TokenType t) {
  if (t < 0 || t >= TOKEN_TYPE_COUNT) return "OUT OF BOUNDS";
  return _TokenTypeTranslation[t];
}
